apiVersion: apps/v1
kind: Deployment
metadata:
  name: d1
spec:
  replicas: 2
  selector:
    matchLabels:
      dish: samosa
  template:
    metadata:
      labels:
        dish: samosa
    spec:
      containers:
      - name: c1
        image: httpd
