apiVersion: v1
kind: Pod
metadata:
  name: ibm
  labels:
    name: www
spec:
  containers:
  - name: www
    image: nginx
    ports:
      - containerPort: 80
        name: www
    volumeMounts:
      - name: nfspv
        mountPath: /usr/share/nginx/html
  volumes:
    - name: nfspv
      persistentVolumeClaim:
        claimName: pvc1
