apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: c1
    image: nginx
    volumeMounts:
    - name: v1
      mountPath: /data      
  volumes:
  - name: v1
    emptyDir: {}
