apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  containers:
  - name: c1
    image: nginx
    volumeMounts:
    - name: v3
      mountPath: /usr/share/ngin/html
    - name: v4
      mountPath: /gulabJamun
  volumes:
  - name: v3
    hostPath:
      path: /samosa
      type: DirectoryOrCreate
  - name: v4
    hostPath:
      path: /sweets
      type: DirectoryOrCreate
